apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 968641182612.dkr.ecr.eu-north-1.amazonaws.com/lumina-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        # Health Probes
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
        # Resource Management
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1536Mi"
        # Environment Variables from Secrets
        env:
        - name: LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: GEMINI_API_KEY
        - name: IMAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: IMAGE_API_KEY
        - name: SERPER_API_KEY
          valueFrom:
            secretKeyRef:
              name: lumina-secrets
              key: SERPER_API_KEY
        - name: LLM_MODEL
          value: "google/gemini-2.0-flash-001"
        - name: LLM_BASE_URL
          value: "https://openrouter.ai/api/v1/chat/completions"
        - name: IMAGE_MODEL
          value: "black-forest-labs/FLUX.1-schnell"
        - name: IMAGE_BASE_URL
          value: "https://router.huggingface.co/hf-inference/models/"
        - name: LOG_LEVEL
          value: "INFO"
